# Base configs
baseurl: "https://5g6zjt8m.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "mitch's photos"
subtitle: ""
author: "mitch"
header:
 title: "mitch's"
 subtitle: "photos"
footer:
 name: "hey, you found my photo repository"
 bio: "Thanks for checking out some of my favorite photos I've taken over the past few years."
 github: "I forked this site template <a href=\"https://github.com/ramswaroop/photography\">from here on GitHub </a>"
web_design: "mitch"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  github: "https://www.github.com/5g6zjt8m"
